import type { Locale } from "@/lib/locale";

const dictionary = {
  en: {
    layout: {
      title: "OpenSentry Repository View",
      subtitle: "Repository metadata and portrait workspace",
      searchPlaceholder: "Search repository name, repo ID, or user login",
      searchButton: "Search",
    },
    common: {
      yes: "Yes",
      no: "No",
      unknown: "Unknown",
      none: "None",
      unavailable: "Unavailable",
      noData: "No data",
      reset: "Reset",
      apply: "Apply",
      backHome: "Back to Home",
      openRisk: "Open Portrait",
      openGithub: "Open on GitHub",
      viewAll: "View All",
      loadNextPage: "Load Next Page",
      noRelatedUsers: "No related users",
      relatedUsers: "Related users",
      by: "by",
      committedBy: "committed by",
      recordedUsers: "Recorded Users",
      currentView: "Current View",
      itemsPerPage: "Items per page",
      page: "Page",
      previous: "Previous",
      next: "Next",
      capabilityDimensions: "Capability Dimensions",
    },
    risk: {
      high: "High",
      medium: "Medium",
      low: "Low",
    },
    tabs: {
      overview: "Overview",
      commits: "Commits",
      issues: "Issues",
      prs: "PRs",
      users: "Users",
      risk: "Portrait",
    },
    home: {
      kicker: "Repository Explorer",
      title: "Browse repositories and portraits before entering a project.",
      description:
        "Start from a few representative repositories, then drill into activity, collaboration, and community signals.",
      searchLabel: "Search",
      liveBadge: "Live API Connected",
      apiErrorBadge: "API Error",
      liveNote: "Data is loading from the live OpenSentry API.",
      apiErrorNote: "The page could not load live repository data.",
      filterTitle: "Discovery Views",
      filterDescription:
        "Switch the homepage by repository signal without entering a repository detail page.",
      repoListTitle: "Recommended Repositories",
      repoListDescription:
        "Each card highlights recent activity, collaboration pressure, and community movement.",
      currentScopeTitle: "Current Scope",
      currentScopeDescription: "Live repository data is currently available.",
      apiErrorTitle: "API Unavailable",
      apiErrorDescription:
        "The page could not reach the OpenSentry API. Please check the backend connection.",
      filters: {
        stars: "Stars",
        activity: "Activity",
        collab: "Collaboration",
        community: "Community",
        updated: "Updated",
      },
      insights: {
        active: "Most active in 12 weeks",
        issues: "Most open issues right now",
        backlog: "Highest PR backlog",
        community: "Fastest star growth in 12 weeks",
      },
    },
    repo: {
      sidebarRepo: "Repository",
      sidebarPortrait: "Portrait",
      repoOverview: "Repository Overview",
      portraitSummary: "Project Portrait Summary",
      portraitSummaryDescription:
        "A quick snapshot of the latest project portrait window and key repository signals.",
      historyTitle: "Repository History",
      historyDescription: "Change over the latest 12 repository metadata snapshots.",
      historyEmpty: "No repository history is available yet.",
      historyCaption: "Shows the latest 12 metadata snapshots for the repository.",
      recentCommits: "Recent Commits",
      openIssues: "Open Issues",
      pullRequests: "Pull Requests",
      repoPortrait: "Repository Portrait",
      snapshotMetrics: "Snapshot Metrics",
      snapshotMetricsDescription:
        "The metrics below come from the latest project portrait and repository metadata.",
      dimensions: {
        activity: "Activity",
        collaboration: "Collaboration",
        community: "Community",
      },
    },
    entities: {
      commits: {
        title: "Commits",
        filterAuthor: "Filter by author ID",
        sortCrawledAt: "Sort by latest crawl",
        sortSha: "Sort by SHA",
        asc: "Ascending",
        desc: "Descending",
        emptyTitle: "No Commits",
        emptyDescription: "No commit snapshots matched the current filter.",
        detail: "Commit Detail",
        metadata: "Commit Metadata",
        portraitAvailable: "Commit Portrait",
        portraitUnavailable: "Commit Portrait Unavailable",
        portraitDescription: "Recent portrait fields for this commit.",
        noExtendedMessage: "No extended commit message.",
        noPortrait: "No portrait result found for this commit.",
        author: "Author",
        committed: "Committed",
        parents: "Parents",
        verified: "Verified",
        tree: "Tree",
        authorId: "Author ID",
        committerId: "Committer ID",
        crawledAt: "Crawled At",
        verification: "Verification",
        signature: "Signature",
        findings: "Semgrep Findings",
        assigmentBy: "by",
      },
      issues: {
        title: "Issues",
        emptyTitle: "No Issues",
        emptyDescription: "No issue snapshots matched the current filter.",
        detail: "Issue Detail",
        body: "Issue Body",
        context: "Repository Context",
        allStates: "All states",
        open: "Open",
        closed: "Closed",
        state: "State",
        comments: "Comments",
        association: "Association",
        created: "Created",
        noBody: "No issue body available.",
      },
      prs: {
        title: "Pull Requests",
        emptyTitle: "No Pull Requests",
        emptyDescription: "No pull request snapshots matched the current filter.",
        detail: "Pull Request Detail",
        body: "PR Body",
        context: "Repository Context",
        allStates: "All states",
        open: "Open",
        closed: "Closed",
        state: "State",
        draft: "Draft",
        association: "Association",
        merged: "Merged",
        noBody: "No pull request body available.",
      },
      users: {
        title: "Users",
        filterRole: "Filter by role",
        emptyTitle: "No Users",
        emptyDescription: "No repository users matched the current filter.",
        detail: "User Detail",
        profile: "Profile",
        portraitAvailable: "User Portrait",
        portraitUnavailable: "User Portrait Unavailable",
        portraitDescription: "Recent portrait fields for this contributor.",
        scoreBreakdown: "Capability Dimensions",
        noScoreBreakdown: "No capability breakdown is available for this user yet.",
        openCommits: "View Commits",
        backToUsers: "Back to Users",
      },
      search: {
        title: "Search",
        queryEmpty: "empty",
        scope: "repository catalog + exact user login lookup",
        noResults: "No Results",
        ready: "Search Ready",
        noResultsDescription:
          "No repositories or exact user logins matched the current query.",
        apiFailed: "The API request failed, so search could not read live data.",
        readyDescription:
          "Search scans the full repository catalog and also checks exact user login matches.",
      },
    },
    roles: {
      author: "Author",
      committer: "Committer",
      assignee: "Assignee",
      closedBy: "Closed by",
      reviewer: "Reviewer",
    },
  },
  "zh-CN": {
    layout: {
      title: "OpenSentry 仓库视图",
      subtitle: "仓库元数据与画像展示平台",
      searchPlaceholder: "搜索仓库名、仓库 ID 或用户 login",
      searchButton: "搜索",
    },
    common: {
      yes: "是",
      no: "否",
      unknown: "未知",
      none: "无",
      unavailable: "暂无",
      noData: "暂无数据",
      reset: "重置",
      apply: "应用",
      backHome: "返回首页",
      openRisk: "查看画像",
      openGithub: "查看 GitHub 仓库",
      viewAll: "查看全部",
      loadNextPage: "加载下一页",
      noRelatedUsers: "暂无关联用户",
      relatedUsers: "关联用户",
      by: "作者",
      committedBy: "提交者",
      recordedUsers: "已收录用户",
      currentView: "当前视角",
      itemsPerPage: "每页条数",
      page: "第",
      previous: "上一页",
      next: "下一页",
      capabilityDimensions: "能力维度",
    },
    risk: {
      high: "高",
      medium: "中",
      low: "低",
    },
    tabs: {
      overview: "总览",
      commits: "提交",
      issues: "Issue",
      prs: "PR",
      users: "用户",
      risk: "画像",
    },
    home: {
      kicker: "仓库发现",
      title: "先看值得关注的仓库，再进入单仓库详情。",
      description: "按活跃度、协作压力和社区变化快速浏览代表性仓库。",
      searchLabel: "搜索",
      liveBadge: "实时数据",
      apiErrorBadge: "接口错误",
      liveNote: "数据来自 OpenSentry 实时接口。",
      apiErrorNote: "当前无法读取实时仓库数据。",
      filterTitle: "发现视角",
      filterDescription: "按不同指标切换首页排序，不需要先进入仓库详情页。",
      repoListTitle: "推荐仓库",
      repoListDescription: "每张卡片聚焦最近活跃度、协作压力和社区变化。",
      currentScopeTitle: "当前范围",
      currentScopeDescription: "当前可读取实时仓库数据。",
      apiErrorTitle: "接口暂不可用",
      apiErrorDescription: "当前无法访问 OpenSentry API，请检查后端连接。",
      filters: {
        stars: "Star",
        activity: "活跃度",
        collab: "协作治理",
        community: "社区关注",
        updated: "最近更新",
      },
      insights: {
        active: "近 12 周提交最频繁",
        issues: "当前 Open Issue 最多",
        backlog: "当前 PR 积压最高",
        community: "近 12 周 Star 增长最快",
      },
    },
    repo: {
      sidebarRepo: "仓库信息",
      sidebarPortrait: "项目画像",
      repoOverview: "仓库总览",
      portraitSummary: "项目画像摘要",
      portraitSummaryDescription: "展示最近一次项目画像窗口中的关键指标。",
      historyTitle: "仓库历史时序",
      historyDescription: "展示最近 12 次抓取到的仓库元数据变化。",
      historyEmpty: "暂时没有可用的仓库历史数据。",
      historyCaption: "最近 12 次抓取的仓库元数据变化。",
      recentCommits: "最近提交",
      openIssues: "Open Issues",
      pullRequests: "Pull Requests",
      repoPortrait: "仓库画像",
      snapshotMetrics: "快照指标",
      snapshotMetricsDescription: "下方指标来自最新项目画像和仓库元数据。",
      dimensions: {
        activity: "活跃度",
        collaboration: "协作治理",
        community: "社区关注",
      },
    },
    entities: {
      commits: {
        title: "提交",
        filterAuthor: "按作者 ID 筛选",
        sortCrawledAt: "按最近抓取排序",
        sortSha: "按 SHA 排序",
        asc: "升序",
        desc: "降序",
        emptyTitle: "暂无提交",
        emptyDescription: "当前筛选条件下没有匹配的提交快照。",
        detail: "提交详情",
        metadata: "提交元数据",
        portraitAvailable: "提交画像",
        portraitUnavailable: "提交画像不可用",
        portraitDescription: "该提交最近一次画像评估结果。",
        noExtendedMessage: "没有扩展提交说明。",
        noPortrait: "当前提交暂无画像结果。",
        author: "作者",
        committed: "提交时间",
        parents: "父提交数",
        verified: "是否验证",
        tree: "Tree",
        authorId: "作者 ID",
        committerId: "提交者 ID",
        crawledAt: "抓取时间",
        verification: "验证信息",
        signature: "签名类型",
        findings: "Semgrep 命中数",
        assigmentBy: "作者",
      },
      issues: {
        title: "Issue",
        emptyTitle: "暂无 Issue",
        emptyDescription: "当前筛选条件下没有匹配的 Issue 快照。",
        detail: "Issue 详情",
        body: "Issue 内容",
        context: "仓库上下文",
        allStates: "全部状态",
        open: "Open",
        closed: "Closed",
        state: "状态",
        comments: "评论数",
        association: "关系",
        created: "创建时间",
        noBody: "暂无 Issue 正文。",
      },
      prs: {
        title: "PR",
        emptyTitle: "暂无 PR",
        emptyDescription: "当前筛选条件下没有匹配的 PR 快照。",
        detail: "PR 详情",
        body: "PR 内容",
        context: "仓库上下文",
        allStates: "全部状态",
        open: "Open",
        closed: "Closed",
        state: "状态",
        draft: "草稿",
        association: "关系",
        merged: "已合并",
        noBody: "暂无 PR 正文。",
      },
      users: {
        title: "用户",
        filterRole: "按角色筛选",
        emptyTitle: "暂无用户",
        emptyDescription: "当前筛选条件下没有匹配的仓库用户。",
        detail: "用户详情",
        profile: "用户资料",
        portraitAvailable: "用户画像",
        portraitUnavailable: "用户画像不可用",
        portraitDescription: "该贡献者最近一次画像评估结果。",
        scoreBreakdown: "能力维度",
        noScoreBreakdown: "当前没有可用的能力维度信息。",
        openCommits: "查看提交",
        backToUsers: "返回用户列表",
      },
      search: {
        title: "搜索",
        queryEmpty: "空",
        scope: "全量仓库目录 + 精确用户 login 查询",
        noResults: "没有结果",
        ready: "搜索就绪",
        noResultsDescription: "当前查询未命中仓库或精确用户 login。",
        apiFailed: "接口请求失败，暂时无法读取实时数据。",
        readyDescription: "搜索会扫描全量仓库目录，并检查是否存在精确匹配的用户 login。",
      },
    },
    roles: {
      author: "作者",
      committer: "提交者",
      assignee: "处理人",
      closedBy: "关闭者",
      reviewer: "评审者",
    },
  },
} as const;

export function getDictionary(locale: Locale) {
  return dictionary[locale];
}

export function getRiskLabel(level: "high" | "medium" | "low", locale: Locale) {
  return getDictionary(locale).risk[level];
}

export function getBooleanLabel(value: boolean, locale: Locale) {
  const t = getDictionary(locale);
  return value ? t.common.yes : t.common.no;
}
