import type { Locale } from "@/lib/locale";

export function getDictionary(locale: Locale) {
  if (locale === "en") {
    return {
      layout: {
        title: "OpenSentry Repository View",
        subtitle: "Repository metadata and portrait workspace",
        searchPlaceholder: "Search repository name or repo ID",
        searchButton: "Search",
      },
      common: {
        yes: "Yes",
        no: "No",
        unknown: "Unknown",
        none: "None",
        unavailable: "Unavailable",
        noData: "No data",
        reset: "Reset",
        apply: "Apply",
        backHome: "Back to Home",
        openRisk: "Open Portrait",
        openGithub: "Open on GitHub",
        viewAll: "View All",
        loadNextPage: "Load Next Page",
        noRelatedUsers: "No related users",
        relatedUsers: "Related users",
        by: "by",
        committedBy: "committed by",
        recordedUsers: "Recorded Users",
        currentView: "Current View",
      },
      risk: {
        high: "High",
        medium: "Medium",
        low: "Low",
      },
      tabs: {
        overview: "Overview",
        commits: "Commits",
        issues: "Issues",
        prs: "PRs",
        users: "Users",
        risk: "Portrait",
      },
      home: {
        kicker: "Repository Explorer",
        title: "Browse repositories, time series, and portraits before entering a repo.",
        description:
          "The homepage focuses on repository discovery, lightweight metrics, and portrait signals from live OpenSentry data.",
        searchLabel: "Repository Search",
        liveBadge: "Live API Connected",
        apiErrorBadge: "API Error",
        liveNote:
          "Repository, portrait, and repository-user data are now loaded directly from OpenSentry.",
        apiErrorNote:
          "The backend request failed. This page now shows only backend-driven data and will not fabricate local fallback repositories.",
        filterTitle: "Discovery Views",
        filterDescription:
          "Switch the homepage by repository signal without entering a repository detail page.",
        repoListTitle: "Repository List",
        repoListDescription:
          "Repository cards combine metadata, project portraits, and recorded user counts.",
        currentScopeTitle: "Current API Scope",
        currentScopeDescription:
          "The homepage is using live project, repository, portrait, and repository-user data.",
        apiErrorTitle: "API Unavailable",
        apiErrorDescription:
          "The page could not reach the OpenSentry API. Check OPENSENTRY_API_BASE_URL and OPENSENTRY_PLATFORM.",
        filters: {
          stars: "Stars",
          activity: "Activity",
          collab: "Collaboration",
          community: "Community",
          updated: "Updated",
        },
        insights: {
          active: "Active This Week",
          issues: "Issue Activity Watch",
          backlog: "PR Backlog Watch",
          community: "Community Growth Watch",
        },
      },
      repo: {
        sidebarRepo: "Repository",
        sidebarPortrait: "Portrait",
        repoOverview: "Repository Overview",
        portraitSummary: "Project Portrait Summary",
        portraitSummaryDescription:
          "The cards below come from the latest project portrait snapshot and observation window.",
        historyTitle: "Repository History",
        historyDescription:
          "Recent crawls of repository metadata, including stars, forks, and open issues.",
        historyEmpty: "No repository history is available yet.",
        recentCommits: "Recent Commits",
        openIssues: "Open Issues",
        pullRequests: "Pull Requests",
        repoPortrait: "Repository Portrait",
        snapshotMetrics: "Snapshot Metrics",
        snapshotMetricsDescription:
          "The metrics below come from the latest project portrait and repository metadata.",
        dimensions: {
          activity: "Activity",
          collaboration: "Collaboration",
          community: "Community",
        },
      },
      entities: {
        commits: {
          title: "Commits",
          filterAuthor: "Filter by author id",
          sortSha: "Sort by SHA",
          sortCreatedAt: "Sort by created_at",
          asc: "Ascending",
          desc: "Descending",
          emptyTitle: "No Commits",
          emptyDescription: "No commit snapshots matched the current filter.",
          detail: "Commit Detail",
          metadata: "Commit Metadata",
          portraitAvailable: "Commit Portrait",
          portraitUnavailable: "Commit Portrait Unavailable",
          portraitDescription: "Commit portrait is the primary trust signal for this commit.",
          noExtendedMessage: "No extended commit message.",
          noPortrait: "No portrait result found for this commit.",
          author: "Author",
          committed: "Committed",
          parents: "Parents",
          verified: "Verified",
          tree: "Tree",
          authorId: "Author ID",
          committerId: "Committer ID",
          crawledAt: "Crawled At",
          verification: "Verification",
          signature: "Signature",
          findings: "Semgrep Findings",
          assigmentBy: "by",
        },
        issues: {
          title: "Issues",
          emptyTitle: "No Issues",
          emptyDescription: "No issue snapshots matched the current filter.",
          detail: "Issue Detail",
          body: "Issue Body",
          context: "Repository Portrait Context",
          allStates: "All states",
          open: "Open",
          closed: "Closed",
          state: "State",
          comments: "Comments",
          association: "Association",
          created: "Created",
          noBody: "No issue body available.",
        },
        prs: {
          title: "Pull Requests",
          emptyTitle: "No Pull Requests",
          emptyDescription: "No pull request snapshots matched the current filter.",
          detail: "Pull Request Detail",
          body: "PR Body",
          context: "Repository Portrait Context",
          allStates: "All states",
          open: "Open",
          closed: "Closed",
          state: "State",
          draft: "Draft",
          association: "Association",
          merged: "Merged",
          noBody: "No pull request body available.",
        },
        users: {
          title: "Users",
          filterRole: "Filter by role",
          emptyTitle: "No Users",
          emptyDescription: "No repository users matched the current filter.",
          detail: "User Detail",
          profile: "User Profile",
          portraitAvailable: "User Portrait",
          portraitUnavailable: "User Portrait Unavailable",
          portraitDescription:
            "User portrait is shown as the primary trust and credibility layer for this contributor.",
          scoreBreakdown: "Score Breakdown",
          noScoreBreakdown: "No user portrait score breakdown is available.",
          openCommits: "Open Commits",
          backToUsers: "Back to Users",
        },
        search: {
          title: "Repository Search",
          queryEmpty: "empty",
          scope: "full repository catalog",
          noResults: "No Results",
          ready: "Search Ready",
          noResultsDescription:
            "No repositories matched the current query in the full scanned repository catalog.",
          apiFailed:
            "The API request failed, so search could not read live repository data.",
          readyDescription:
            "Search scans the full repository catalog and links directly into repository overview pages.",
        },
      },
      roles: {
        author: "Author",
        committer: "Committer",
        assignee: "Assignee",
        closedBy: "Closed by",
        reviewer: "Reviewer",
      },
    } as const;
  }

  return {
    layout: {
      title: "OpenSentry 仓库视图",
      subtitle: "仓库元数据与画像展示平台",
      searchPlaceholder: "搜索仓库名或仓库 ID",
      searchButton: "搜索",
    },
    common: {
      yes: "是",
      no: "否",
      unknown: "未知",
      none: "无",
      unavailable: "暂无",
      noData: "暂无数据",
      reset: "重置",
      apply: "应用",
      backHome: "返回首页",
      openRisk: "查看画像",
      openGithub: "查看 GitHub 仓库",
      viewAll: "查看全部",
      loadNextPage: "加载下一页",
      noRelatedUsers: "暂无关联用户",
      relatedUsers: "关联用户",
      by: "作者",
      committedBy: "提交者",
      recordedUsers: "已收录用户",
      currentView: "当前视角",
    },
    risk: {
      high: "高",
      medium: "中",
      low: "低",
    },
    tabs: {
      overview: "总览",
      commits: "提交",
      issues: "Issue",
      prs: "PR",
      users: "用户",
      risk: "画像",
    },
    home: {
      kicker: "仓库发现",
      title: "在进入仓库前，先浏览仓库、时序信息与画像内容。",
      description:
        "首页聚焦仓库发现、轻量指标和来自 OpenSentry 的实时画像信号。",
      searchLabel: "仓库搜索",
      liveBadge: "已连接实时接口",
      apiErrorBadge: "接口错误",
      liveNote: "首页已经直接读取仓库、画像和仓库用户数据。",
      apiErrorNote:
        "后端请求失败。首页现在只展示后端真实数据，不再伪造本地回退仓库。",
      filterTitle: "发现视角",
      filterDescription: "按不同仓库信号切换首页视角，无需先进入仓库详情页。",
      repoListTitle: "仓库列表",
      repoListDescription: "仓库卡片结合了 metadata、项目画像与已收录用户数。",
      currentScopeTitle: "当前接口范围",
      currentScopeDescription:
        "首页已经接入实时的项目、仓库、项目画像和仓库用户数据。",
      apiErrorTitle: "接口不可用",
      apiErrorDescription:
        "页面暂时无法访问 OpenSentry API。若要查看实时数据，请检查 OPENSENTRY_API_BASE_URL 和 OPENSENTRY_PLATFORM。",
      filters: {
        stars: "Star",
        activity: "活跃度",
        collab: "协作治理",
        community: "社区关注",
        updated: "最近更新",
      },
      insights: {
        active: "本周活跃仓库",
        issues: "Issue 活跃观察",
        backlog: "PR Backlog 观察",
        community: "社区增长观察",
      },
    },
    repo: {
      sidebarRepo: "仓库信息",
      sidebarPortrait: "项目画像",
      repoOverview: "仓库总览",
      portraitSummary: "项目画像摘要",
      portraitSummaryDescription: "下面的卡片来自最新项目画像快照及其观测窗口。",
      historyTitle: "仓库历史时序",
      historyDescription: "最近抓取的仓库 metadata，包括 Star、Fork 和 Open Issue。",
      historyEmpty: "暂时没有可用的仓库历史数据。",
      recentCommits: "最近提交",
      openIssues: "Open Issues",
      pullRequests: "Pull Requests",
      repoPortrait: "仓库画像",
      snapshotMetrics: "快照指标",
      snapshotMetricsDescription: "下方指标来自最新项目画像和仓库元数据。",
      dimensions: {
        activity: "活跃度",
        collaboration: "协作治理",
        community: "社区关注",
      },
    },
    entities: {
      commits: {
        title: "提交",
        filterAuthor: "按作者 ID 筛选",
        sortSha: "按 SHA 排序",
        sortCreatedAt: "按 created_at 排序",
        asc: "升序",
        desc: "降序",
        emptyTitle: "暂无提交",
        emptyDescription: "当前筛选条件下没有匹配的提交快照。",
        detail: "提交详情",
        metadata: "提交元数据",
        portraitAvailable: "提交画像",
        portraitUnavailable: "提交画像不可用",
        portraitDescription: "提交画像作为该提交的主要可信度信号展示。",
        noExtendedMessage: "没有扩展提交说明。",
        noPortrait: "当前提交暂无画像结果。",
        author: "作者",
        committed: "提交时间",
        parents: "父提交数",
        verified: "是否验证",
        tree: "Tree",
        authorId: "作者 ID",
        committerId: "提交者 ID",
        crawledAt: "抓取时间",
        verification: "验证信息",
        signature: "签名类型",
        findings: "Semgrep 命中数",
        assigmentBy: "作者",
      },
      issues: {
        title: "Issue",
        emptyTitle: "暂无 Issue",
        emptyDescription: "当前筛选条件下没有匹配的 Issue 快照。",
        detail: "Issue 详情",
        body: "Issue 内容",
        context: "仓库画像上下文",
        allStates: "全部状态",
        open: "Open",
        closed: "Closed",
        state: "状态",
        comments: "评论数",
        association: "关系",
        created: "创建时间",
        noBody: "暂无 Issue 正文。",
      },
      prs: {
        title: "PR",
        emptyTitle: "暂无 PR",
        emptyDescription: "当前筛选条件下没有匹配的 PR 快照。",
        detail: "PR 详情",
        body: "PR 内容",
        context: "仓库画像上下文",
        allStates: "全部状态",
        open: "Open",
        closed: "Closed",
        state: "状态",
        draft: "草稿",
        association: "关系",
        merged: "合并时间",
        noBody: "暂无 PR 正文。",
      },
      users: {
        title: "用户",
        filterRole: "按角色筛选",
        emptyTitle: "暂无用户",
        emptyDescription: "当前筛选条件下没有匹配的仓库用户。",
        detail: "用户详情",
        profile: "用户资料",
        portraitAvailable: "用户画像",
        portraitUnavailable: "用户画像不可用",
        portraitDescription: "用户画像作为该贡献者的主要可信与特征层展示。",
        scoreBreakdown: "评分拆解",
        noScoreBreakdown: "当前没有可用的用户画像评分拆解。",
        openCommits: "查看提交",
        backToUsers: "返回用户列表",
      },
      search: {
        title: "仓库搜索",
        queryEmpty: "空",
        scope: "全量仓库目录",
        noResults: "没有结果",
        ready: "搜索已就绪",
        noResultsDescription: "当前查询在全量仓库目录中没有匹配项。",
        apiFailed: "接口请求失败，因此搜索无法读取实时仓库数据。",
        readyDescription: "当前搜索会扫描全量仓库目录，并直接跳转到仓库总览页。",
      },
    },
    roles: {
      author: "作者",
      committer: "提交者",
      assignee: "处理人",
      closedBy: "关闭者",
      reviewer: "评审者",
    },
  } as const;
}

export function getRiskLabel(level: "high" | "medium" | "low", locale: Locale) {
  return getDictionary(locale).risk[level];
}

export function getBooleanLabel(value: boolean, locale: Locale) {
  const t = getDictionary(locale);
  return value ? t.common.yes : t.common.no;
}
